services:
  web:
    build: .
    depends_on:
      - chrome
      - db
      - webpacker
    env_file:
      - config/docker.env
    ports:
      - "3000:3000"
    volumes:
      - "./:/app/"

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - ./:/app/
    ports:
      - "3035:3035"

  db:
    image: postgres:13
    env_file:
      - config/docker.env
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
volumes:
  # Volume to hold the Postgres database on the host system
  data:
